name: Create release on tag push

on:
  push:
    tags:
      - 'release/*'

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c release

      - name: Run tests
        run: dotnet test

      - name: Create NuGet package
        run: dotnet pack -c release

      - name: Push NuGet package
        run: dotnet nuget push "Edna/bin/Release/alterNERDtive.EDNA.*.nupkg" --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_AUTH_TOKEN}}

      - name: Get release body
        run: |
          echo "release_body=$(cat CHANGELOG.md)" >> "$GITHUB_ENV"

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.1'

      - name: Draft release
        uses: https://gitea.com/actions/release-action@main
        with:
          body: ${{ env.release_body }}
          files: |-
            Edna/bin/Release/alterNERDtive.EDNA.*.nupkg
          draft: true
          api_key: '${{ secrets.RELEASE_TOKEN }}'
