name: Run tests on push

on:
  push

jobs:
  build:
    name: Test EDNA
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c release

      - name: Run tests
        run: dotnet test
