name: Create release on tag push

on:
  push:
    tags:
      - 'release/*'

jobs:
  build:
    name: Build EDNA
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c release

      - name: Run tests
        run: dotnet test

      - name: Create NuGet package
        run: dotnet pack -c release

      - name: Push NuGet package
        run: dotnet nuget push "Edna\bin\Release\alterNERDtive.EDNA.*.nupkg" --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_AUTH_TOKEN}}

      - name: Draft release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Edna/bin/Release/alterNERDtive.EDNA.*.nupkg"
          bodyFile: "CHANGELOG.md"
          draft: true
          token: ${{ secrets.RELEASE_TOKEN }}
